<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CutAssistantNext.Core\CutAssistantNext.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HanumanInstitute.LibMpv" Version="0.10.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
